# This is a basic workflow to help you get started with Actions

name: Check broken links

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  broken_link_checker_job:
    runs-on: ubuntu-latest
    name: Check for broken links
    steps:
    - name: Check for broken links
      id: link-report
      uses: celinekurpershoek/link-checker@v1.0.1
      with:
        # Required:
        url: 'https://pikalinkdu06.github.io/CartoGeo/index.html'
        recursiveLinks: true # Check all URLs on all reachable pages (could take a while)
    - name: Get the result
      run: echo "${{steps.link-report.outputs.result}}"
